mikejac/node-red-contrib-google-smarthome

- lib/HttpActions.js
When somebody sends a POST request without authorization header to the /smarthome endpoint, it prints an error message ("Cannot read property 'split' of undefined") including a full stacktrace. Since a few days somebody tries to scan my home. This fills my log pretty quick with useless stacktraces.
> Check for missing authentication header

- README.md
- google-smarthome.js
- lib/Devices.js
- locales/en-US/window.json
- package.json
- window.html
- window.js
I added windows as supported devices. Windows can be opened or closed (fully or to a certain percentage value) and queried for their state.
Windows with multiple opening directions (blinds like [this one](https://developers.google.com/assistant/smarthome/images/smarthome-top-down-bottom-up-blinds.png)) not implemented yet.
> Add window as supported device

- README.md
- google-smarthome.html
- lib/HttpActions.js
I improved the documentation a little bit:
- Added a table of contents to Readme
- Added example flows for thermostats, windows and outlets to Readme (not for the other nodes because I don't use them). Partly fixes #5.
- Added an introduction to Readme. Fixes #19.
- Added help text to management node. Fixes #10?
- Extended the troubleshooting section in Readme.
- Add a note about the opened port to Readme. Clears up #6.
- Fixed an error message that was saying "HttpActions:requestSync(): error; [object Object]", without the actual object
You can see the full Readme at https://github.com/Caprico85/node-red-contrib-google-smarthome.
> Improve Docs

- google-smarthome.js
- lib/Auth.js
- lib/HttpActions.js
- lib/HttpAuth.js
- lib/SmartHome.js
Fixed compatibility with Node.js 12.
The problem was that `GoogleSmartHome` inherits from `EventEmitter`. Inheritance is done using Aggregation.js. This class uses `getOwnPropertyNames` and `getOwnPropertySymbols` to collect all properties of all classes it should inherit from. Until Node.js 10 `getOwnPropertySymbols` always returned an empty array. Since Node.js 12 `getOwnPropertySymbols` returns a symbol for the class `EventEmitter`. Aggregation.js then calls `match()` on that symbol. But since symbols don't have a String representation, there is nothing to call `match()` on.
The easiest way would be to remove the call to `getOwnPropertySymbols`. I tried that and it works. But I don't know what these symbols are used for and if it may have any negative effects to simply skip them.
Since …
> Fix compatibility with Node.js 12

- README.md
- vacuum.html
Fans and vacuums were missing from the Readme.
Also added a note about running in Docker to the readme.
> Add fan and vacuum to Readme

- lib/HttpActions.js
For vacuum is mandatory for locator, dock, etc... maybe for other device
> Add "command" from Google in payload

- README.md
- fan.js
- lib/Devices.js
- light.html
- light.js
- locales/en-US/fan.json
- locales/en-US/vacuum.json
- outlet.js
- scene.js
- thermostat.js
- vacuum.js
- window.js
Some changes related to devices.
Commit 71c645e478c869f50a2c95dba3fd400772c6f3d1:
If you try to update the state of a device with an object and set no topic, an error `TypeError: msg.topic.split is not a function` occured.
Commit 5d7494cd69724d8be30021a0cacc0ee5fa906ac3:
Vacuums and fans had no labels in the editor, because no translations were set.
Commit 02b6c297a0b56e9ae7dbd77a70ceb4c9c30e2fc9:
HSV lights had no parameter "value" (the "V" in "HSV").
Commit e48ca24dfa0dda4eb12193e57877122efa325387:
ColorTemp lights were missing from the Readme.
> Device related changes

- README.md
- google-smarthome.html
- google-smarthome.js
- lib/Auth.js
- lib/HttpActions.js
- lib/HttpAuth.js
- lib/SmartHome.js
- lib/frontend/login.html
- locales/en-US/google-smarthome.json
- locales/it_IT/google-smarthome.json
Hi,
this pull request allows us to use the same port used by Node-RED. Is uses the same expressjs HTTP server, and avoid the need to start a new HTTP server.
I've added a path prefix, in order to don't conflict with other paths already used, the default path prefix is "smarthome".
Thanks
Claudio
> Use same node red port and url (with an optional path)

- fan.js
- lib/Devices.js
- light.js
- outlet.js
- scene.js
- thermostat.js
- vacuum.js
- window.js
Hi,
this update adds the device name to the node output message.
The node name helps to decrease the nodes used for the logic. In my flows, I use the same node name for Google, Alexa, and MQTT.
Thanks
Claudio
> Device name

- sensor.js
GS expects humity integer values and was not handling the float values.
Added fix to sensor.js.
In future it may make sense to change formatvalues.js to always return
integer values for Formats.INT case, but since this would impact other
nodes I've applied change only in sensor.js
> Fix Sensor humidity reporting of float values

- devices/shutter.js
- lib/Devices.js
- lib/HttpActions.js
moving "command" outside of payload to prevent other / wrong states leaking into reportState()
example: shutter.js
In my opinion, the information about the used 'command' is better kept outside the payload.
As a next step, we could check whether the payload / the states only contain informations that are specified in the registerDevice function.
This solves the following "HttpActions.js; Line 436":
```
// TODO: This now causes '"code":400,"message":"Request contains an invalid argument."' errors. Parts of the command, e.g. 'onoff' end up in the devices status
//       data, which in turn makes google complain when doing a reportState.
//
// since some commands won't deliver any parameters (like dock or locate), the payload should include the command name.
//payLoadDevice.states.command = …
```
> moving "command" outside of payload.

- devices/media.js
- lib/HttpActions.js
Hi,
I think I've detected a mistake in the _execDevice, please review carefully before merging it.
The problem I've found is in the following rows:
if (command.hasOwnProperty('params')) {
let cur_device=this._devices[device.id] || { "states":{} };
Object.keys(command.params).forEach(function (key) {
// arrgggghhhh - why Google, why ...
if (key === 'color' && command.params.color.hasOwnProperty('spectrumHSV')) {
command.params.color.spectrumHsv = command.params.color.spectrumHSV;
delete command.params.color.spectrumHSV;
}
// if (command.params.hasOwnProperty(key)) {         //  Original Line
if (cur_device.states.hasOwnProperty(key)) {               // New Line
curDevice.states[key] = command.params[key];
}
});
}
Because the forEach is for command.params, it always has the key property, I …
> Fix _execDevice for Media Devices and other nodes

- devices/device.js
There is a small typo for the openPercent state.
> Fixed typo. undedined must be undefined

- README.md
- devices/device.js
- lib/HttpActions.js
- test/sh/device_test.sh
- test/sh/flows.json
Hi,
this patch allows changing the camera auth token in the device node and when a device node receives a GetCameraStream command, send it in the output.
> Camera update token and send message

- google-smarthome.html
Dear,
Thanks for sharing this magnificent node!
I started using it a couple of days ago, and until now it works like a charm...
This pull request simply shows the section headers a bit more explicit, by using [fieldset](https://www.w3schools.com/tags/tag_fieldset.asp) tags:
That way it is a bit more visible which input fields belong together.
There are other Node-RED nodes ([mp4frag](https://github.com/kevinGodell/node-red-contrib-mp4frag), [letsencrypt](https://github.com/bartbutenaers/node-red-contrib-letsencrypt), ...) that use this way of working.
I hope you like it...
P.S. Don't know why, but Github shows a lot of differences (when using the difference comparison in this PR), however the code changes are minimal.  For example this original code snippet:
Has been converted to this: …
> group elements in fieldsets

- devices/device.js
- google-smarthome.html
- google-smarthome.js
- lib/SmartHome.js
- lib/frontend/login.html
- locales/en-US/google-smarthome.html
- locales/en-US/google-smarthome.json
- locales/it_IT/google-smarthome.json
Hi,
the patch allows the management node to send a set_state message if a device state change (after some delay). 
This message can be persisted if needed and can be passed into the management node to restore the persisted state.
There are the following two timers:
- after 10 seconds of a node deployment, request sync is sent to Google in order to align all the devices' properties. 
- after 30 seconds of a state update (state change), a "set_state" message is sent to the management node output to allow the save the new state.
I'm not sure if I should insert those timers' duration in the configuration GUI?
Thanks
> set_state message

- lib/HttpActions.js
This PR sync a dummy node (Google device scene) if no nodes exist.
This should prevent the link error in case no nodes exist.
> sync a dummy node if no nodes exist

- devices/baseDevice.js
- devices/device.html
- devices/locales/en-US/device.json
- devices/locales/it-IT/device.json
This PR does:
- shows the "No traits selected" message if no trait is selected, issue #215 
- don't send a message in output if pass-thru is unchecked, issues #220 and #221.
- manage correctly the thermostatMode changes
> No trait selected, passthru, thermostatMode

- devices/baseDevice.js
- devices/device.html
- devices/locales/en-US/device.html
- devices/locales/en-US/device.json
- devices/locales/it-IT/device.html
- devices/locales/it-IT/device.json
- google-smarthome.js
- lib/Devices.js
- locales/en-US/google-smarthome.html
- locales/it_IT/google-smarthome.html
This PR adds the flag "Persistent State" to the device node. In this way, only the enabled node state will be included in the set_state message sent from the management node.
I've also added a parameter to the get_state message to the management node, if the payload is true, only the state of the nodes with the "Persistent State" flag enabled will be included in the output.
This should simplify the solution of the #227
> Added the Persistent State flag

- devices/camera.html
- devices/media.html
With this PR, the Camera and Media Devices nodes will have a RED triangle, showing that the nodes are deprecated, like the following:
This should speed up the migration progress.
> camera and media devices deprecation warning

- devices/baseDevice.js
This PR should enable to send the SetState after the node receives a command from Google.
Unfortunately in the "updated" function seems that this is not equal to the node object, so "me.persistent_state" is undefined.
After removing all the deprecated nodes, we can change the general code to fix #205.
> ScheduleGetState

- package.json
node-RED has introduced a quality check (scoreboard rating) to indicate that contrib nodes are reaching the minimum specs expected by the node-RED team.
I added an example flow previously (1 point when the depreciated nodes have been removed), and these two additions will improve the SH score by a further 2 points.
See https://discourse.nodered.org/t/introducing-node-scorecards-and-a-new-node-naming-convention/57559/28
For consideration...
> Improve node-RED contrib node compliance

- README.md
- lib/Auth.js
- lib/HttpActions.js
- lib/SmartHome.js
- local-execution/app.js
- test/google-home.json
Reading the [Local fulfillment documentation](https://developers.google.com/assistant/smarthome/concepts/local) I've read the sentence "No modification of your hardware is expected to integrate local fulfillment.".
In the [Add local fulfillment to your smart home Action documentation](https://developers.google.com/assistant/smarthome/develop/local#update_sync_response_in_the_cloud_fulfillment)  the SYNC response custom data contains the authToken.
Why don't use the authToken field to deliver the access token and use the original smart-home path?
In this way, we have no authenticated path where everyone can send commands to the smart home.
I've added auth token for the local request, this token is updated every time a sync request is received.
Unfortunately, I'm not able to test it …
> local_smarthome path replaced by the original smarthome path

- local-execution/app.js
The previous commit changed  the const "version" in "VERSION" without updating the constructor call
> fix: version is not defined

- lib/Devices.js
If the filter topic is enabled in a node, the setState message sent to a management node don't update the node state.
This PR fixes it.
Claudio
> Fix setState don't update the state if the filter topic is enabled

- local-execution/app.js
String.substr was (start, length)
String.substring is (start, end)
This fixes local execution not working on the latest app.js
> Fix usage of .substring in app.js

- devices/device.js
If " Filter incoming messages by topic" is enabled, there is no way to send commands to the node, like the "GetState" or "SetChallengePin" commands.
With this fix, it is possible to use the msg.payload.topic field because the msg.topic must match the configured topic.
> Use payload.topic if filter topic is enabled
