mikejac/node-red-contrib-google-smarthome

lib/HttpActions.js
package.json

I messed it up a bit with my last pull request. I'm sorry. Because of a missing assignment, authentication didn't work anymore at all. This fixes it.

Fix authentication checking

---

google-smarthome.js
lib/Devices.js
light.html
light.js

I've added a light type that is able to receive color temperature instead of a color.

Added light with color temperature setting

---

README.md
google-smarthome.js
lib/Devices.js
locales/en-US/thermostat.json
package.json
thermostat.html
thermostat.js

Added thermostat.
Switching between modes (heat, cool, off, ...) not implemented yet. You can only set the target temperature or ask for target and current temperature. But I guess that already covers a lot of use cases.

Add thermostat

---

google-smarthome.js
lib/Devices.js
lib/HttpActions.js
package.json
vacuum.html
vacuum.js

Some commands, like dock oder locate, will have no parameters. This change will always deliver the command name inside the payload, so the flow can evaluate the command. And also fix failures if there are no parameters present.
This groundwork to support vacuums.

Insert Googles command name into payload 

---

lib/Devices.js
vacuum.html

I sadly messed up the Devices.js. This pull request fixes that. There is also an update for the help of the vacuum device.

Fixed broken Devices.js and updated help vor vacuum

---

fan.html
fan.js
google-smarthome.js
lib/Devices.js
package.json

Support On/Off Fan devices. Based on the Light On/Off implementation

Add support for On/Off FAN device type

---

google-smarthome.html
google-smarthome.js
lib/Auth.js
lib/HttpAuth.js
lib/SmartHome.js
locales/en-US/google-smarthome.json

Hi,
I've modified the handleRefreshToken function in order to return the current accesstoken, in according to the [Implement OAuth account linking.](https://developers.google.com/assistant/smarthome/develop/implement-oauth#implement_oauth_account_linking)
Thanks
Claudio

refresh_token request returns the current access token

---

google-smarthome.html
google-smarthome.js
lib/Auth.js
lib/HttpActions.js
lib/HttpAuth.js
lib/SmartHome.js
lib/frontend/login.html
locales/en-US/google-smarthome.json
locales/it_IT/fan.json
locales/it_IT/google-smarthome.json
locales/it_IT/light.json
locales/it_IT/outlet.json
locales/it_IT/scene.json
locales/it_IT/thermostat.json
locales/it_IT/vacuum.json
locales/it_IT/window.json

Hi,
I guess I've found the problem of the INVALID_ARGUMENT error from google.
When the plugin receives a command from the Google Home App via the /smarthome link, the command itself is saved in the state property of the device.
When the reportState function executes, it send also this value as the status of the device.
```
HttpActions:httpActionsRegister(/smarthome): request.headers = {"host":"smart-home.chimera.dynu.com","x-forwarded-for":"66.249.93.76","connection":"upgrade","content-length":"349","content-type":"application/json;charset=UTF-8","google-assistant-api-version":"v1","authorization":"Bearer BBBBBBBBBBBBBBBBBBBB","user-agent":"Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)","accept-encoding":"gzip,deflate,br"} …
```

Invalid argument problem fixed, i hope

---

google-smarthome.html
google-smarthome.js
lib/Auth.js
lib/HttpActions.js
lib/HttpAuth.js
lib/SmartHome.js
lib/frontend/login.html
locales/en-US/google-smarthome.json
locales/it_IT/fan.json
locales/it_IT/google-smarthome.json
locales/it_IT/light.json
locales/it_IT/outlet.json
locales/it_IT/scene.json
locales/it_IT/thermostat.json
locales/it_IT/vacuum.json
locales/it_IT/window.json

Hi,
this pull request should include all my fix until now.
I've tested with my phone, and the login seems ok.
Thanks
Claudio

Compliant with oauth documentation

---

google-smarthome.html
google-smarthome.js
lib/Auth.js
lib/HttpAuth.js
lib/SmartHome.js
locales/en-US/google-smarthome.json

Hi,
I've fixed all the auth account linking issues, I hope.
The token expiration, the redirect_uri checks, the problem preventing to write the google-smarthome*.json, if doesn't exist.
I hope that you agree to merge it.
Thanks
Claudio

O auth account linking

---

google-smarthome.html
google-smarthome.js
lib/Auth.js
lib/HttpAuth.js
lib/SmartHome.js
locales/en-US/google-smarthome.json
locales/it_IT/fan.json
locales/it_IT/google-smarthome.json
locales/it_IT/light.json
locales/it_IT/outlet.json
locales/it_IT/scene.json
locales/it_IT/thermostat.json
locales/it_IT/vacuum.json
locales/it_IT/window.json

Hi,
this change return invalid grant in case of error, as requested.
Claudio

Invalid grant

---

google-smarthome.html
google-smarthome.js
lib/Auth.js
lib/HttpAuth.js
lib/SmartHome.js
locales/en-US/google-smarthome.json

Hi,
I've added the access token duration, according to the Google documentation [Implement OAuth account linking](https://developers.google.com/assistant/smarthome/develop/implement-oauth#implement_oauth_account_linking)
There is still missing the token validity.
I hope all is ok.

Access token duration

---

package.json

This adds a keyword required by: https://flows.nodered.org/add/node  
See: https://nodered.org/docs/creating-nodes/packaging#packagejson

Add to Node-RED registry

---

README.md
google-smarthome.html

Hi,
I've added some logic to the settings GUI. 
The SSL keys will be hidden if the "Use external SSL offload" is checked
The "Use http Node-RED root path" and "SSL section" will be hidden if the "Port" is empty or equals to 0 or less.
Thanks
Claudio

Dynamic Settings GUI

---

README.md
google-smarthome.html
google-smarthome.js
lib/Auth.js
lib/HttpActions.js
lib/HttpAuth.js
lib/SmartHome.js
lib/frontend/login.html
locales/en-US/google-smarthome.json
locales/it_IT/google-smarthome.json
package.json

Hi,
this request is to integrate the Google login in the project.
It is allowed to login only to one user for now. In order to allow more users to login, we need to update the access and refresh token part.
Thanks
Claudio

Google login

---

README.md
package.json
sensor.html
sensor.js

Adds support for sensor devices supporting temperature and/or humidity reporting

Add Sensor support (temperature and humidity)

---

thermostat.js

Some object properties got mismatched.
This PR fixes this.
Fixes #67

Fix thermostat set or other topics

---

README.md
devices/shutter.html
devices/shutter.js
package.json

Add Shutter support

---

README.md
devices/locales/en-US/shutter.json
devices/locales/en-US/switch.json
devices/switch.html
devices/switch.js
package.json

Add Device Support: Switch

---

README.md
devices/light.html
devices/light.js

Hi,
I've added a light that can receive a color temperature or an RGB value. This is useful for some modern Zigbee lamps.

Added a light for RGB and Temperature

---

devices/outlet.js
devices/thermostat.js

`thermostat.js`
Fix for bug #85 and added additional status information.
Node Status:
T - Temperature Ambient
S - Setpoint
---
`outlet.js`
Keep node state updates consistent.
---

Keep node state updates consistent.

---

README.md
devices/camera.html
devices/camera.js
devices/locales/en-US/camera.json
devices/locales/it_IT/camera.json
lib/Devices.js
lib/HttpActions.js
package.json

Hi,
this patch adds camera support.
I've added the action.devices.commands.GetCameraStream execute command.
Thanks
Claudio

Added camera

---

devices/sensor.js
devices/shutter.js
devices/window.js

Fix "ReferenceError: states is not defined" @  updateStatusIcon() for some devices.

 Fix "ReferenceError: states is not defined" @  updateStatusIcon() 

---

README.md
devices/fireplace.html
devices/fireplace.js
devices/hood.html
devices/hood.js
devices/locales/en-US/fireplace.json
devices/locales/en-US/hood.json
package.json

I have added 2 new devices : Kitchen Hood and Fireplace.
I may need help to add additional Trait to the devices (but this may be a requirment for all devices).
I'm glad to help.
Guys are you on any chat server ? (discord, telegram, slack...?),
G.

New device (hood & fireplace)

---

devices/camera.html
devices/camera.js
devices/locales/en-US/camera.json
devices/locales/it_IT/camera.json

Hi,
I've added the App IDs in the node editor.
Claudio

Added AppIds to the camera node

---

README.md
google-smarthome.html

Hi,
this is just a doc fix, added better info on google login and a reference link on the google config node.
Some of this is also part of my previous pull request.
Best Regards
Claudio

Better docs on google login

---

devices/media.js
devices/scene.js
google-smarthome.js
lib/Auth.js
lib/Devices.js
lib/HttpActions.js
lib/SmartHome.js

Hi,
with this patch, the command parameters are copied on the payload, if not present yet.
Best Regards
Claudio

Fix no current channel in payload

---

devices/light.html
devices/light.js
devices/locales/en-US/light.json
devices/locales/it_IT/light.json
formatvalues.js
google-smarthome.js

Hi,
I've added a new light node with the device type parameter.
Thanks
Claudio

Added one light node for all types

---

devices/media.html
devices/media.js
google-smarthome.js
lib/Devices.js
lib/HttpActions.js

Hi,
this is the fix of bug #113 
Thanks
Claudio

Fix Playback commands #113

---

README.md
google-smarthome.html

Minor spelling typos & clearer definition of Jwt key file (I was a little confused about which was the jwt file when I installed smarthome)

Minor spelling typos in readme

---

devices/device.js
test/device_spec.js

Hi,
this fix the set currentRunCycle.

Fix set currentRunCycle

---

devices/locales/en-US/sensor.json
devices/locales/it-IT/sensor.json

The locales for the sensor device are currently missing.

Add locales for sensor device

---

README.md
devices/blind.js
devices/light.js

Hi,
some copy & past error fix.

fix ReferenceError: me is not defined

---

devices/device.html
devices/device.js
devices/locales/en-US/device.json
devices/locales/it-IT/device.json
test/sh/device_test.sh

Hi,
this should fix the fan speed settings.
Thanks
Claudio

Bug Fix Fan Speed

---

devices/device.js
test/sh/device_test.sh
test/sh/flows.json

Hi 
this patch fixes the following issue:
ArmDisarm not working properly,
It is possible to assign an array to an object and vice versa
added some notification events for ObjectDetection, RunCycle, SensorState, LockUnlock, NetworkControl, OpenClose
Bye
Claudio

Fix ArmDisarm, added notifications, no obj-array type exchange

---

devices/device.html
devices/device.js
google-smarthome.html
test/sh/device_test.sh
test/sh/google-home.json

Hi,
this patch fixes some errors (sent also in the previous patch) and adds the value type structure to better check the status update.
Claudio

State type

---

devices/device.js
test/sh/device_test.sh

Hi,
this request contains small enhancements and more test checks.
Thanks
Claudio

Optional states

---

lib/frontend/login.html

Hi,
this patch migrates to the new Google Identity Services library, as requested by Google.
Best Regards
Claudio

Migrate to the new Google Identity Services library

---

devices/device.js

Hi,
this fixes a small typo.
Claudio

transport_control typo

---

google-smarthome.html
google-smarthome.js
lib/SmartHome.js
locales/it_IT/google-smarthome.json

Hi,
this PR disables the advanced settings by default.
There are also some small changes on the HTTP path, just to clarify the code.

Disabled advanced settings by default,

---

devices/device.js
lib/HttpActions.js
lib/HttpAuth.js
lib/SmartHome.js
test/sh/device_test.sh

Hi,
this replaces the path.join function with an ad-hoc version fixing the #188 bug

path.join fix

---

devices/light.js

Ensure we don't access this.states.color.spectrumHsv if undefined

---

devices/baseDevice.js
devices/device.html
devices/locales/en-US/device.json
devices/locales/it-IT/device.json
lib/HttpActions.js

Hi,
this should fix the issue #208 .
I've implemented it for the Google Device node.

Secondary User Verification

---

devices/baseDevice.js
lib/Devices.js
package.json

this PR fixes the #208 regarding the following points:
- the status under the node indicate "unknown"
- "If msg arrives on input, pass through to output:" does not function and I have seen that in other nodes as well.

Fix unknow status for armLevel and passthru

---

devices/baseDevice.js
devices/device.html

This PR Hide the PIN field if no PIN challenge is selected

Hide the PIN field if no PIN challenge is selected

---

devices/baseDevice.js

This PR adds the sensor state fixing the #245

sensorstate state

---

devices/baseDevice.js

sensorstate status fix

---

lib/SmartHome.js

I think the me constant is missing.

mdns missing me

---

devices/baseDevice.js
google-smarthome.js
lib/Auth.js
lib/HttpActions.js
lib/HttpAuth.js
lib/SmartHome.js
test/sh/device_test.sh

Sometimes I get the error "Missing SmartHome", so I've converted the GoogleSmartHomeNode MgmtNode to classes hoping the error never appears anymore.

GoogleSmartHomeNode MgmtNode converted to classes

---

google-smarthome.html
google-smarthome.js
locales/en-US/google-smarthome.html
locales/en-US/google-smarthome.json
locales/it_IT/google-smarthome.html
locales/it_IT/google-smarthome.json

This PR is the same as #263 without the #262.
The users can choose the format of the persistent data (the set_state automatic message) to allow them to use it for storing in the persistent storage and use in other logic easily.

Set state type

---

devices/device.js

Status of "Lock" unknown fix

---

local-execution/app.js

Hi,
This fix the issue #345 
I'm sorry for that.
Claudio

mDNS local fulfillment fix

---

devices/device.html
devices/device.js
devices/locales/en-US/device.json
devices/locales/it-IT/device.json

Added the OccupancySensing trait. See https://developers.home.google.com/cloud-to-cloud/traits/occupancysensing for more info

OccupancySensing

---

README.md
devices/device.html
devices/device.js
devices/locales/en-US/device.json

https://developers.home.google.com/cloud-to-cloud/guides/gameconsole?hl=ru

support action.devices.types.GAME_CONSOLE
